# Generated by Django 5.1.2 on 2024-12-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateField()),
                ('idcliente', models.IntegerField()),
                ('idempleado', models.IntegerField()),
                ('listaproducto', models.IntegerField()),
                ('totalventa', models.IntegerField()),
            ],
        ),
    ]
