# Generated by Django 5.1.2 on 2024-12-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('gama', models.CharField(max_length=10)),
                ('precios', models.IntegerField()),
                ('idproveedor', models.IntegerField()),
                ('idinventario', models.IntegerField()),
            ],
        ),
    ]
