# Generated by Django 5.1.2 on 2024-12-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('correoelectronico', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fechacontratacion', models.DateField()),
            ],
        ),
    ]
