# Generated by Django 5.1.2 on 2024-12-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('correoelectrónico', models.CharField(max_length=20)),
                ('dirección', models.CharField(max_length=50)),
                ('listasproductos', models.TextField(max_length=500)),
                ('edad', models.SmallIntegerField()),
            ],
        ),
    ]
