# Generated by Django 5.1.2 on 2024-12-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='correoelectrónico',
            new_name='correoelectronico',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
